name: Custom Playwright Action Test
on:
  pull_request:
    branches: [main]

jobs:
  ai-playwright:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: AI Playwright
        uses: johndennehy101/ai-playwright-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          llm-api-key: ${{ secrets.LLM_API_KEY }}
          llm-host: ${{ secrets.LLM_HOST }}
          model-id: ${{ secrets.MODEL_NAME }}
          exclude-pattern: ^versions/
          include-existing-tests: 'true' 
          include-source-files: 'true'
          test-file-suffixes: '.spec'
          test-file-roots: 'app/e2e'